plugins {
    id 'com.android.application'
}

android {
    namespace 'com.thomas.outdoortile'
    compileSdk 34

    defaultConfig {
        applicationId "com.thomas.outdoortile"
        minSdk 29
        targetSdk 34
        versionCode 6
        versionName "2.5"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {}