plugins {
    id 'com.android.application'
}

android {
    namespace 'com.thomas.outdoortile'
    compileSdk 34

    defaultConfig {
        applicationId "com.thomas.outdoortile"
        minSdk 26
        targetSdk 34
        versionCode 25
        versionName "2.6"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}